version: '3.4'

services:
  backend:
    image: matchmaker_fastapi
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000

  frontend:
    image: matchmaker_vue
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080

  database:
    image: postgres:15.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - 5432:5432

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  volumes:
    postgres: